### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mrc4tt** [sarisia/actions-status-discord#207]
Hi.

Are it's possible to set ``${{ job.status }}`` - so It will display on actions, if it has been success or failed?

Because it does not work for me. ;/

**Comment by sarisia** [comment]
Hi,

We pick `${{ job.status }}` by default and shows the value in embed title.

Check the `action.yml` for how it works:
https://github.com/sarisia/actions-status-discord/blob/master/action.yml#L9-L12

If your workflow fails, you'll get the embed as shown below by default:
![image](https://user-images.githubusercontent.com/33576079/137367344-1fecea45-4c87-444c-b808-2102df13c3f5.png)

**Comment by mrc4tt** [comment]
Hi. Sorry for bump again @sarisia 

Do you know, about it's possible to setup, so it will show what error/failure?
