### ISSUE TITLE
Tag user or role on discord

### ISSUE THREAD

**Issue by sarisia** [sarisia/actions-status-discord#398]
### Discussed in https://github.com/sarisia/actions-status-discord/discussions/387

<div type='discussions-op-text'>

<sup>Originally posted by **murilomorato** December 15, 2022</sup>
I created a server to receive alerts whenever a deploy fails, but I haven't been receiving notifications alerts.
I tried to insert inside the 'description' prop my Role tag and my user id. They arrive tagged in the discord message, but it does not generate the notification, as I believe the message arrives as a kind of 'quote', not as a normal message.

Have you tried any alternatives yet? 

Thanks😉</div>

**Comment by jmg-duarte** [comment]
Hey @sarisia is it possible to make this work per-author? I don't work alone and would like to have Discord tag the right user from a mapping between author and discord ID or similar.
